# Generated by Django 6.1.1 on 2026-09-23 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('rules', models.TextField(verbose_name='Rules')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Balance')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Strategy',
                'verbose_name_plural': 'Strategies',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'title'), name='uq_strategy_user_title'), models.CheckConstraint(condition=models.Q(('balance__gte', 5)), name='chk_strategy_balance')],
            },
        ),
    ]
