# Generated by Django 6.1.1 on 2026-09-23 23:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='test_days',
            field=models.IntegerField(default=1, verbose_name='Test Days'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='strategy',
            constraint=models.CheckConstraint(condition=models.Q(('test_days__gte', 1)), name='chk_strategy_test_days'),
        ),
    ]
