# Generated by Django 6.1.1 on 2026-09-24 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategies', '0002_strategy_test_days_strategy_chk_strategy_test_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=10, verbose_name='Deal Type')),
                ('pair', models.CharField(choices=[('XAUUSD', 'XAU/USD'), ('EURGBP', 'EUR/GBP'), ('EURJPY', 'EUR/JPY'), ('EURAUD', 'EUR/AUD'), ('EURCHF', 'EUR/CHF'), ('EURUSD', 'EUR/USD'), ('GBPCHF', 'GBP/CHF'), ('AUDJPY', 'AUD/JPY'), ('CADJPY', 'CAD/JPY'), ('NZDJPY', 'NZD/JPY'), ('USDTRY', 'USD/TRY'), ('USDZAR', 'USD/ZAR'), ('USDMXN', 'USD/MXN'), ('USDSGD', 'USD/SGD'), ('USDNOK', 'USD/NOK')], max_length=8, verbose_name='Pair')),
                ('from_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='From Price')),
                ('to_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='To Price')),
                ('is_followed_rules', models.BooleanField(default=True, verbose_name='Is Followed Rules')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('img', models.ImageField(blank=True, null=True, upload_to='chart/images/%Y%m%d', verbose_name='Chart Image')),
                ('result', models.BooleanField(default=True, verbose_name='Result')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='strategies.strategy')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('from_price__gt', models.F('to_price')), ('deal_type', 'BUY')), models.Q(('from_price__lt', models.F('to_price')), ('deal_type', 'SELL')), _connector='OR'), name='chk_deal_from_price_to_price')],
            },
        ),
    ]
