# Generated by Django 6.1.1 on 2026-09-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
        ('strategies', '0002_strategy_test_days_strategy_chk_strategy_test_days'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deal',
            name='chk_deal_from_price_to_price',
        ),
        migrations.AddConstraint(
            model_name='deal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('from_price__lt', models.F('to_price')), ('deal_type', 'BUY')), models.Q(('from_price__gt', models.F('to_price')), ('deal_type', 'SELL')), _connector='OR'), name='chk_deal_from_price_to_price'),
        ),
    ]
