# Generated by Django 6.1.1 on 2026-09-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_remove_deal_chk_deal_from_price_to_price_and_more'),
        ('strategies', '0002_strategy_test_days_strategy_chk_strategy_test_days'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='deal',
            constraint=models.CheckConstraint(condition=models.Q(('from_price__gt', 0)), name='chk_deal_from_price'),
        ),
        migrations.AddConstraint(
            model_name='deal',
            constraint=models.CheckConstraint(condition=models.Q(('to_price__gt', 0)), name='chk_deal_to_price'),
        ),
    ]
