# Generated by Django 6.1.1 on 2026-09-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_deal_chk_deal_from_price_deal_chk_deal_to_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Amount'),
            preserve_default=False,
        ),
    ]
