# Generated by Django 6.1.1 on 2026-09-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_deal_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='to_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='To Price'),
        ),
    ]
