# Generated by Django 6.1.1 on 2026-09-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_alter_deal_amount_alter_deal_to_price'),
        ('strategies', '0002_strategy_test_days_strategy_chk_strategy_test_days'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='deal',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='chk_deal_amount'),
        ),
    ]
