# Generated by Django 6.1.1 on 2026-09-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0007_alter_deal_result'),
        ('strategies', '0002_strategy_test_days_strategy_chk_strategy_test_days'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deal',
            name='chk_deal_from_price_to_price',
        ),
        migrations.AlterField(
            model_name='deal',
            name='result',
            field=models.CharField(choices=[('PRF', 'Profit'), ('LOS', 'Loss'), ('EVE', 'Even')], max_length=6, verbose_name='Result'),
        ),
        migrations.AddConstraint(
            model_name='deal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('from_price__lt', models.F('to_price')), ('deal_type', 'BUY'), ('result', 'PRF')), models.Q(('from_price__gt', models.F('to_price')), ('deal_type', 'SELL'), ('result', 'PRF')), models.Q(('from_price__gt', models.F('to_price')), ('deal_type', 'BUY'), ('result', 'LOS')), models.Q(('from_price__lt', models.F('to_price')), ('deal_type', 'SELL'), ('result', 'LOS')), models.Q(('amount', 0), ('from_price', models.F('to_price')), ('result', 'EVE')), _connector='OR'), name='chk_deal_from_price_to_price'),
        ),
    ]
