# Generated by Django 6.1.1 on 2026-10-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0008_remove_deal_chk_deal_from_price_to_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='is_followed_rules',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=5, verbose_name='Is Followed Rules'),
        ),
    ]
